Traceback (most recent call last):
  File "/home/phantomfeed/PycharmProjects/PythonAdvanced/mod5/tests4task4.py", line 10, in test_can_read_stdout_file
    raise Exception('Hello stderr.txt')
Exception: Hello stderr.txt
